source 'https://supermarket.chef.io'

metadata

cookbook 'apt', '~> 3.0.0'
cookbook 'auto-patch', '~> 0.1.10'
cookbook 'firewall', '~> 2.5.0'
cookbook 'memcached', '~>2.1.0'
cookbook 'apache2', '~> 3.1.0'
cookbook 'python', '~> 1.4.6'
cookbook 'build-essential', '~>3.2.0'
cookbook 'uwsgi', '~>0.1.2'
cookbook 'aws', '~>3.3.1'
cookbook 'aws-codedeploy-agent', '~> 0.4.1'
